### ISSUE TITLE
Please update for version Godot 3.1.1

### ISSUE THREAD

**Issue by esbvaGames** [nobuyukinyuu/gdsmod#6]
Error loading ModReplayer.tscn

![image](https://user-images.githubusercontent.com/5530499/67964385-f7c97f80-fbde-11e9-8450-edfd99174b53.png)

**Comment by nobuyukinyuu** [comment]
Works here, `3.1.1.stable.official`, 64-bit.  Please give more information.  Line 83 of ModPlayer.tscn refers to a `DynamicFont` subresource which is located at line 12 of the same file, which looks like this:

```gdscript
[sub_resource type="DynamicFont" id=1]
size = 24
outline_size = 1
outline_color = Color( 0.564706, 0.658824, 1, 1 )
use_filter = true
extra_spacing_char = -1
extra_spacing_space = 4
font_data = ExtResource( 2 )
```
ExtResource(2) is `res://ELEKTORA.ttf`.

There's no reason why this would fail to load under normal circumstances.  Please verify that the above information is correct.

**Comment by esbvaGames** [comment]
[image: image.png]

No open un version 3.1.1

**Comment by esbvaGames** [comment]
![Error_ModReplayer](https://user-images.githubusercontent.com/5530499/68093486-a508f580-fe74-11e9-9b9c-1389f9dcc7eb.png)

New fileError in version Godot 3.1.1  version 64bits !!!

**Comment by nobuyukinyuu** [comment]
Please use version 3.1.1.  In the screenshot, it appears you are using version 3.1.  Audio stream generators are not supported in version 3.1.
